version: "2"
services:
  angular-service:
    # The name of the service
    container_name: angularcontainer # Container name
    build: . # Location of our Dockerfile
    volumes:
      # Volume binding
      - './ProjetDevops:/usr/src/app'
    ports:
      - '4200:4200' # Port mapping